### ISSUE TITLE
API_KEY not set, API_SECRET not set

### ISSUE THREAD

**Issue by dmalan** [cs50/help50#236]
```
$ ./tweets asdf
Traceback (most recent call last):
  File "./tweets", line 45, in <module>
    main()
  File "./tweets", line 19, in main
    tweets = helpers.get_user_timeline(screen_name, 50)
  File "/root/helpers.py", line 45, in get_user_timeline
    raise RuntimeError("API_KEY not set")
RuntimeError: API_KEY not set
````

**Comment by dmalan** [comment]
https://github.com/cs50/help50/commit/6c0763f8b7cee550cad9942f0a7ab39dd188aeb4
